### ISSUE TITLE
How to get bsv compiler software ?

### ISSUE THREAD

**Issue by Jrebort** [georgia-tech-synergy-lab/MAERI#1]
Hello！ I didn't find the download link of bsv compiler software on the bluespec website. The download link has expired. In order to use your library more conveniently, can you provide a reliable way to obtain bsv?

**Comment by hyoukjun** [comment]
Hi JreBort,

Bluespec Compiler is a commercial tool so we cannot provide the license from our side. They provide free university license so please refer to this website for more information: https://bluespec.com/university/ 

Thank you,
Hyoukjun

**Comment by Jrebort** [comment]
Ok, thanks！
